# Generated by Django 4.2.9 on 2024-01-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaqCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256)),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "Faq Card",
                "verbose_name_plural": "Faq Cards",
            },
        ),
        migrations.CreateModel(
            name="FaqLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("url", models.URLField(max_length=256)),
                ("position", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Faq Link",
                "verbose_name_plural": "Faq Links",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="StatsDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waste_weight",
                    models.PositiveIntegerField(verbose_name="Waste weight"),
                ),
                ("bsd_count", models.PositiveIntegerField(verbose_name="Bsd Count")),
                (
                    "company_count",
                    models.PositiveIntegerField(verbose_name="Company Count"),
                ),
                ("retrieved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Stat digest",
                "verbose_name_plural": "Stat digests",
            },
        ),
        migrations.CreateModel(
            name="VideoLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=256)),
                ("position", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Video Link",
                "verbose_name_plural": "Video Links",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="FaqCardLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("url", models.URLField(default="En savoir plus", max_length=256)),
                (
                    "icon_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bsdd", "Bsdd"),
                            ("Bsda", "Bsda"),
                            ("Bsff", "Bsff"),
                            ("Bsdasri", "Bsdasri"),
                            ("Bsvhu", "Bsvhu"),
                            ("Bspaoh", "Bspao"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.faqcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faq Card Link",
                "verbose_name_plural": "Faq Card Links",
            },
        ),
    ]
