# Generated by Django 4.2.9 on 2024-01-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqcardlink",
            name="label",
            field=models.CharField(default="En savoir plus", max_length=50),
        ),
        migrations.AlterField(
            model_name="faqcardlink",
            name="url",
            field=models.URLField(max_length=256),
        ),
    ]
