# Generated by Django 4.2.9 on 2024-01-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_faqcardlink_label_alter_faqcardlink_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faqcard",
            options={
                "ordering": ["position"],
                "verbose_name": "Faq Card",
                "verbose_name_plural": "Faq Cards",
            },
        ),
        migrations.AddField(
            model_name="faqcard",
            name="position",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="faqcardlink",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="website.faqcard",
            ),
        ),
    ]
