# Generated by Django 4.2.9 on 2024-01-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_faqcard_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faqcard",
            name="position",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="faqcardlink",
            name="icon_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bsdd", "Bsdd"),
                    ("Bsda", "Bsda"),
                    ("Bsff", "Bsff"),
                    ("Bsdasri", "Bsdasri"),
                    ("Bsvhu", "Bsvhu"),
                    ("Bspaoh", "Bspaoh"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="faqlink",
            name="position",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="videolink",
            name="position",
            field=models.PositiveIntegerField(),
        ),
    ]
