# Generated by Django 4.0.1 on 2022-05-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_page_level_page_lft_page_parent_page_rght_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"verbose_name": "Page", "verbose_name_plural": "Pages"},
        ),
        migrations.RemoveField(
            model_name="page",
            name="position",
        ),
    ]
