# Generated by Django 4.0.1 on 2022-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_page_options_remove_page_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={
                "ordering": ["position"],
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
            },
        ),
        migrations.AddField(
            model_name="link",
            name="position",
            field=models.PositiveSmallIntegerField(null=True, verbose_name="Position"),
        ),
    ]
