# Generated by Django 4.0.1 on 2022-05-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_link_options_link_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="link",
            new_name="target",
        ),
    ]
