# Generated by Django 4.1.1 on 2022-09-15 08:07

import martor.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_rename_link_link_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="text",
            field=martor.models.MartorField(blank=True),
        ),
    ]
