# Generated by Django 4.1.1 on 2022-11-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_page_display_contact_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="link_anchor",
            field=models.CharField(
                blank=True,
                help_text="Override Title to display as link",
                max_length=200,
                verbose_name="Link Anchor",
            ),
        ),
    ]
