# Generated by Django 4.1.1 on 2022-11-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_page_link_anchor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Link",
        ),
    ]
