# Generated by Django 4.1.1 on 2023-01-23 17:20

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_delete_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Nom de l'utilisateur"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=250,
                        verbose_name="Email de l'utilisateur",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Établissement de l'utilisateur",
                    ),
                ),
                (
                    "siret",
                    models.EmailField(
                        blank=True,
                        max_length=250,
                        verbose_name="Siret de l'utilisateur",
                    ),
                ),
                (
                    "subject",
                    models.TextField(blank=True, verbose_name="Objet du message"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "origin_page_title",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Page d'appel du formulaire",
                    ),
                ),
                ("origin_page_id", models.UUIDField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created"],
            },
        ),
    ]
