# Generated by Django 4.1.6 on 2023-05-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="bsds",
            field=models.CharField(blank=True, max_length=300, verbose_name="Bsds"),
        ),
    ]
