# Generated by Django 4.1.1 on 2022-12-22 13:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webinar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="Titre du webinaire"),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(verbose_name="Date et heure du webinaire"),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=120, verbose_name="Durée prévue en mn"
                    ),
                ),
                (
                    "display_days_before",
                    models.PositiveSmallIntegerField(
                        default=28, verbose_name="Afficher X jours avant"
                    ),
                ),
                ("visio_link", models.URLField(blank=True, verbose_name="Lien visio")),
            ],
            options={
                "verbose_name": "Webinaire",
                "verbose_name_plural": "Webinaire",
                "ordering": ("-scheduled_at",),
            },
        ),
    ]
